services:
  otomato-proxy:
    build:
      context: ./envoy
      dockerfile: Dockerfile.proxy
    volumes:
      - ./envoy/envoy-remote.yaml:/etc/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "18000:80"
      - "18001:8001"

  echo-service:
    image: otomato/http-echo
    command:
      - '-text="Welcome to WASM land"'
    networks:
      envoymesh:
        aliases:
          - echo-service
    expose:
      - "5678"
    ports:
      - "18080:5678"

networks:
  envoymesh: {}
